include $(TOPDIR)/rules.mk
 
PKG_NAME:=tuya-sdk
PKG_VERSION:=1.0.0
PKG_RELEASE:=1
PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL:=https://github.com/tuya/tuya-iot-core-sdk.git
PKG_SOURCE_VERSION:=0208badefb2003d30e70b5b875395e3187c850d9
CMAKE_BINARY_SUBDIR:=$(PKG_BUILD_DIR)/build
include $(INCLUDE_DIR)/package.mk
include $(INCLUDE_DIR)/cmake.mk
CMAKE_INSTALL:=1

define Package/tuya-sdk
	CATEGORY:=Examples
	TITLE:=tuya-sdk
endef

define Pakcage/tuya-sdk/description
	Tools to connect to the Tuya cloud
endef

define Build/InstallDev
	
	$(INSTALL_DIR) $(1)/usr/lib $(1)/usr/include 
	$(INSTALL_BIN) $(PKG_BUILD_DIR)/build/lib/*.so $(1)/usr/lib/
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/utils/*.h $(1)/usr/include/
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/include/*.h $(1)/usr/include/
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/libraries/coreJSON/source/include/*.h $(1)/usr/include/
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/interface/*.h $(1)/usr/include/
endef

define Package/tuya-sdk/install
	$(INSTALL_DIR) $(1)/usr/lib
	$(INSTALL_BIN) $(PKG_BUILD_DIR)/build/lib/*.so $(1)/usr/lib/

endef

$(eval $(call BuildPackage,tuya-sdk))
